/**
 * Security Alert Module
 *
 * Sends structured email alerts for security events:
 *   - RATE_LIMIT_AUTH   — auth endpoint hit the 20-req/15min limit
 *   - RATE_LIMIT_API    — API endpoint hit the 120-req/min limit
 *   - WEBHOOK_SIG_FAIL  — invalid webhook signature (Fireblocks or Sumsub)
 *   - SUSPICIOUS_IP     — request from an unexpected IP (future use)
 *
 * Debouncing: same event code is suppressed for DEBOUNCE_MS (default 5 min)
 * so a flood of bad requests does not trigger a flood of emails.
 *
 * All events are still console-logged regardless of the debounce state.
 */

import { sendMail, getRecipient } from './mailer.js';

// ─── Types ────────────────────────────────────────────────────────────────────

export type AlertLevel = 'warning' | 'critical';

export type AlertCode =
  | 'RATE_LIMIT_AUTH'
  | 'RATE_LIMIT_API'
  | 'WEBHOOK_SIG_FAIL_FIREBLOCKS'
  | 'WEBHOOK_SIG_FAIL_SUMSUB'
  | 'SUSPICIOUS_IP';

export interface SecurityAlertOptions {
  code: AlertCode;
  level?: AlertLevel;
  ip?: string;
  path?: string;
  detail?: string;
}

// ─── Debounce state ───────────────────────────────────────────────────────────

const DEBOUNCE_MS = 5 * 60 * 1000; // 5 minutes per alert code
const lastSent = new Map<AlertCode, number>();

function isDebounced(code: AlertCode): boolean {
  const last = lastSent.get(code);
  if (!last) return false;
  return Date.now() - last < DEBOUNCE_MS;
}

function markSent(code: AlertCode): void {
  lastSent.set(code, Date.now());
}

// ─── Formatters ───────────────────────────────────────────────────────────────

const CODE_LABELS: Record<AlertCode, string> = {
  RATE_LIMIT_AUTH:            'Auth Rate Limit Triggered',
  RATE_LIMIT_API:             'API Rate Limit Triggered',
  WEBHOOK_SIG_FAIL_FIREBLOCKS:'Fireblocks Webhook Signature Invalid',
  WEBHOOK_SIG_FAIL_SUMSUB:    'Sumsub Webhook Signature Invalid',
  SUSPICIOUS_IP:              'Suspicious IP Address Detected',
};

function buildSubject(level: AlertLevel, code: AlertCode): string {
  const emoji = level === 'critical' ? '🚨' : '⚠️';
  return `${emoji} [KryptoKnight Security] ${CODE_LABELS[code]}`;
}

function buildBody(level: AlertLevel, opts: SecurityAlertOptions): string {
  const ts = new Date().toISOString();
  const lines = [
    `<h2 style="color:${level === 'critical' ? '#c0392b' : '#e67e22'}">`,
    `  ${level === 'critical' ? '🚨 CRITICAL' : '⚠️ WARNING'}: ${CODE_LABELS[opts.code]}`,
    `</h2>`,
    `<table style="border-collapse:collapse;font-family:monospace;font-size:13px">`,
    row('Time (UTC)', ts),
    row('Alert Code', opts.code),
    row('Severity', level.toUpperCase()),
    opts.ip   ? row('Source IP', opts.ip)   : '',
    opts.path ? row('Path',      opts.path) : '',
    opts.detail ? row('Detail', opts.detail) : '',
    `</table>`,
    `<hr/>`,
    `<p style="font-size:12px;color:#666">`,
    `This alert is automatically generated by the KryptoKnight API security monitor.<br/>`,
    `Alerts of the same type are suppressed for 5 minutes after first occurrence.`,
    `</p>`,
  ].filter(Boolean);
  return lines.join('\n');
}

function row(label: string, value: string): string {
  return `<tr>
    <td style="padding:4px 12px 4px 0;font-weight:bold;color:#555">${label}</td>
    <td style="padding:4px 0;color:#222">${escHtml(value)}</td>
  </tr>`;
}

function escHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Send a security alert email (debounced per alert code).
 * Always logs to console; email is skipped if the same code fired < 5 min ago.
 */
export async function sendSecurityAlert(opts: SecurityAlertOptions): Promise<void> {
  const level: AlertLevel = opts.level ?? 'warning';
  const { code, ip, path, detail } = opts;

  // Always log
  const logPrefix = level === 'critical' ? '[SECURITY CRITICAL]' : '[SECURITY WARNING]';
  console.warn(
    `${logPrefix} ${code}`,
    [ip && `ip=${ip}`, path && `path=${path}`, detail && `detail=${detail}`]
      .filter(Boolean).join(' | ') || ''
  );

  // Debounce email
  if (isDebounced(code)) {
    console.warn(`[SECURITY] ${code} email suppressed (debounce 5 min)`);
    return;
  }

  try {
    const to = await getRecipient();
    await sendMail({
      to,
      subject: buildSubject(level, code),
      html: buildBody(level, opts),
    });
    markSent(code);
    console.log(`[SECURITY] Alert email sent → ${to} (${code})`);
  } catch (err) {
    console.error(`[SECURITY] Failed to send alert email for ${code}:`, err);
  }
}
